#!name=快手去广告
#!desc=移除开屏广告、视频流广告、底栏皮肤、精简我的页面。
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/KuaiShou.png
#!category=iKeLee
#!openUrl=https://apps.apple.com/app/id440948110
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://github.com/luestr/ProxyResource/blob/main/README.md
#!date=2025-03-06 17:08:34

[URL Rewrite]
# 任务中心 - 挂件
^https:\/\/az2-api\.ksapisrv\.com\/rest\/n\/taskCenter\/task\/report\? - reject-dict
# 广告下发
^https:\/\/az2-api\.ksapisrv\.com\/rest\/n\/ad\/ - reject-dict

[Script]
body_rewrite_17 = type=http-response, pattern=^https:\/\/az2-live\.ksapisrv\.com\/rest\/n\/live\/feed\/square\/refresh\?, script-path=https://raw.githubusercontent.com/usklsvg/Plugins/refs/heads/main/script/body-rewrite-sr.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-del%22%2C%5B%22data.banners%22%5D%5D%5D

body_rewrite_25 = type=http-response, pattern=^https:\/\/az2-api-js\.gifshow\.com\/rest\/n\/user\/profile\/v2\?, script-path=https://raw.githubusercontent.com/usklsvg/Plugins/refs/heads/main/script/body-rewrite-sr.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-del%22%2C%5B%22postRecommends%22%5D%5D%5D

[MITM]
hostname = %APPEND% az4-api.ksapisrv.com, az4-api-idc.ksapisrv.com, az2-api.ksapisrv.com, az2-api-idc.ksapisrv.com, apissl.gifshow.com, apissl.ksapisrv.com, az2-api-js.gifshow.com, az2-live.ksapisrv.com

