#!name=收银通商户端去广告
#!desc=移除开屏广告和首页推广
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/ShouYinTongMerchant.png
#!category=iKeLee
#!openUrl=https://apps.apple.com/app/id1539897140
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://github.com/luestr/ProxyResource/blob/main/README.md
#!date=2024-11-28 00:00:00

[URL Rewrite]
^https:\/\/syt\.leshuazf\.com\/merchant\/merchant\/showOpenScreenAd$ - reject-dict
^https:\/\/m\.fqfin\.cn\/cls\/leshuapay\/preCredit\.json$ - reject-dict
^https:\/\/syt\.leshuazf\.com\/merchant\/messageCenter\/stationLetterList$ - reject-dict
^https:\/\/syt\.leshuazf\.com\/merchant\/merchant\/getBannerConfig$ - reject-dict
^https:\/\/syt\.leshuazf\.com\/merchant\/popup\/getPopupInfo$ - reject-dict

[MITM]
hostname = %APPEND% syt.leshuazf.com, m.fqfin.cn

