#!name=小蚕霸王餐去广告
#!desc=移除开屏广告、首页横幅推广、红包推广、更新弹窗。
#!author=Sliverkiss[https://github.com/Sliverkiss],可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/XiaoCan.png
#!category=iKeLee
#!open=https://apps.apple.com/app/id1618414236
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://github.com/luestr/ProxyResource/blob/main/README.md
#!date=2024-11-28 00:00:00

[URL Rewrite]
# 首页横幅推广
^https:\/\/web2\.realtech-inc\.com\/oss\/xc-app-assets\/configs\/common\/theme\.json - reject-dict
# 开屏广告
^https:\/\/sdk\.1rtb\.net\/sdk\/req_ad\? - reject-dict
# 更新弹窗
^https:\/\/gw\.xiaocantech\.com\/g\/pa - reject-dict

[MITM]
hostname = %APPEND% gw.xiaocantech.com, web2.realtech-inc.com, sdk.1rtb.net

