name: Update Module

on:
  schedule:
    - cron: '30 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: xream/script-hub:latest
        ports:
          - 9100:9100
          - 9101:9101
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Wait for Docker service to be ready
      run: sleep 10

    - name: Check Docker service status
      run: docker ps -a

    - name: Check Docker logs for issues
      run: docker logs $(docker ps -q --filter ancestor=xream/script-hub:latest)
    
    - name: Run Python script
      run: |
        python script/module.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: '152701112+usklsvg@users.noreply.github.com'
        message: 'Update Modules'
        push: true  # Ensure this is set to true to enable pushing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
